'use client';
import { useMemo, useState } from 'react';
const clamp=(n:number,min=0,max=1e12)=>Math.min(max,Math.max(min,Number.isFinite(n)?n:min));
const fmt=(n:number,d=0)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(n);
export function PublisherRevenueCalculator(){
 const [pageviews,setPageviews]=useState(100000),[units,setUnits]=useState(2),[eligible,setEligible]=useState(95),[fill,setFill]=useState(70),[ecpm,setEcpm]=useState(1.5),[share,setShare]=useState(100),[target,setTarget]=useState(1000);
 const r=useMemo(()=>{const pv=clamp(pageviews),u=clamp(units,0,20),er=clamp(eligible,0,100)/100,fr=clamp(fill,0,100)/100,e=clamp(ecpm,0,1000),s=clamp(share,0,100)/100;const opp=pv*u;const eligibleImp=opp*er;const filled=eligibleImp*fr;const gross=filled/1000*e;const revenue=gross*s;const rpm=pv?revenue/pv*1000:0;const unfilled=Math.max(0,eligibleImp-filled);const needGross=s?clamp(target)/s:0;const needFilled=e?needGross/e*1000:0;return{opp,eligibleImp,filled,gross,revenue,rpm,unfilled,needFilled}},[pageviews,units,eligible,fill,ecpm,share,target]);
 const input=(label:string,v:number,set:(n:number)=>void,suffix?:string,step='1')=><label><span>{label}</span><div><input type="number" min="0" step={step} value={v} onChange={e=>set(clamp(Number(e.target.value)))} />{suffix&&<b>{suffix}</b>}</div></label>;
 return <div className="prc" id="revenue-calculator"><style>{CSS}</style><div className="prc-head"><span>PUBLISHER REVENUE CALCULATOR</span><h2>Estimate eCPM, fill and publisher revenue from your own assumptions</h2><p>Use this planning calculator to model inventory. Results are estimates, not a Boost RAVA revenue or fill-rate guarantee.</p></div><div className="prc-grid"><div className="prc-form">{input('Monthly pageviews',pageviews,setPageviews)}{input('Ad opportunities per page',units,setUnits,undefined,'0.1')}{input('Eligible delivery rate',eligible,setEligible,'%','0.1')}{input('Fill rate',fill,setFill,'%','0.1')}{input('eCPM',ecpm,setEcpm,'per 1,000','0.01')}{input('Publisher revenue share',share,setShare,'%','0.1')}</div><div className="prc-results" aria-live="polite"><article><small>Ad opportunities</small><strong>{fmt(r.opp)}</strong></article><article><small>Eligible impressions</small><strong>{fmt(r.eligibleImp)}</strong></article><article><small>Filled impressions</small><strong>{fmt(r.filled)}</strong></article><article><small>Unfilled impressions</small><strong>{fmt(r.unfilled)}</strong></article><article><small>Gross modeled revenue</small><strong>{fmt(r.gross,2)}</strong></article><article className="primary"><small>Estimated publisher revenue</small><strong>{fmt(r.revenue,2)}</strong></article><article><small>Revenue / 1,000 pageviews</small><strong>{fmt(r.rpm,2)}</strong></article></div></div><div className="prc-reverse"><div>{input('Target monthly publisher revenue',target,setTarget,undefined,'1')}</div><p>At the current eCPM and revenue-share assumptions, the model requires about <strong>{fmt(r.needFilled)} filled impressions</strong>.</p></div><div className="prc-formulas"><article><h3>Publisher revenue formula</h3><p><b>Filled impressions = Pageviews × ad opportunities/page × eligible rate × fill rate</b></p><p><b>Gross revenue = Filled impressions ÷ 1,000 × eCPM</b></p><p><b>Publisher revenue = Gross revenue × publisher revenue share</b></p></article><article><h3>What is eCPM?</h3><p>eCPM expresses revenue per 1,000 impressions. For realized data: <b>eCPM = Revenue ÷ Impressions × 1,000</b>.</p><p>Fill rate describes the share of eligible ad opportunities that receive an ad. Neither metric is guaranteed.</p></article></div></div>
}
const CSS=`.prc{--ink:#0e1d3b;--muted:#64748b;--line:#dbe5f1;max-width:1180px;margin:0 auto;padding:6px 0}.prc *{box-sizing:border-box}.prc-head{max-width:790px;margin-bottom:26px}.prc-head>span{font-size:11px;font-weight:900;letter-spacing:.14em;color:#345edb}.prc-head h2{margin:9px 0 12px;font-size:clamp(32px,4vw,52px);line-height:1.05;color:var(--ink)}.prc-head p{color:var(--muted);line-height:1.7}.prc-grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:18px}.prc-form{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:20px;border:1px solid var(--line);border-radius:20px;background:#fff}.prc-form label{display:grid;gap:7px;font-size:12px;font-weight:800;color:#334155}.prc-form label>div{display:flex;align-items:center;border:1px solid #cbd7e5;border-radius:11px;overflow:hidden;background:#fff}.prc-form input{width:100%;min-width:0;border:0;outline:0;padding:13px;font-size:16px;color:#0f172a}.prc-form label b{padding:0 11px;color:#64748b;font-size:10px;white-space:nowrap}.prc-results{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.prc-results article{padding:17px;border:1px solid var(--line);border-radius:16px;background:#f8fbff}.prc-results article.primary{background:#0e2b64;color:#fff;border-color:#0e2b64}.prc-results small,.prc-results strong{display:block}.prc-results small{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#718096}.prc-results .primary small{color:#bfd0ef}.prc-results strong{margin-top:7px;font-size:23px}.prc-reverse{display:grid;grid-template-columns:320px 1fr;gap:18px;align-items:center;margin-top:14px;padding:18px;border-radius:16px;background:#eef4ff}.prc-reverse .prc-form{display:block;padding:0;border:0;background:transparent}.prc-reverse p{margin:0;color:#3f4f67;line-height:1.65}.prc-formulas{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.prc-formulas article{padding:18px;border:1px solid var(--line);border-radius:16px;background:#fff}.prc-formulas h3{margin:0 0 8px;color:var(--ink)}.prc-formulas p{margin:7px 0;color:var(--muted);font-size:13px;line-height:1.65}@media(max-width:850px){.prc-grid,.prc-reverse,.prc-formulas{grid-template-columns:1fr}.prc-reverse{align-items:stretch}}@media(max-width:560px){.prc-form,.prc-results{grid-template-columns:1fr}.prc-results strong{font-size:20px}}`;
